MCKIN-24508 missing translations added
edx-solutions/xblock-drag-and-drop-v2 pull request #252
Opened 2020-09-22 06:52 UTC by musmanmalik

missing translations added

2020-09-22 12:48 UTC, wasifarbisoft requested changes
Some minor comments!

2020-09-22 12:48 UTC, wasifarbisoft commented on drag_and_drop_v2/translations/ar/LC_MESSAGES/text.po
> +msgstr "لا يمكنك إضافة أي عناصر أخرى إلى هذه المنطقة."
I wonder if "." is part of arabic!
Same for other arabic translations

2020-09-22 12:48 UTC, wasifarbisoft commented on drag_and_drop_v2/translations/es_419/LC_MESSAGES/text.po
> +msgstr "键盘说明"
Is this Spanish?

2020-09-23 07:48 UTC, wasifarbisoft commented
@musmanmalik ,
looks good to me!

2020-09-23 07:49 UTC, wasifarbisoft approved these changes

2020-09-23 07:55 UTC, merged

2020-09-23 07:55 UTC, musmanmalik commented
@wasifarbisoft https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/251 a copy of this PR need to review as well.